### PR TITLE
cleanup warnings

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov v.tolstov@selfip.ru

### CODE REVIEW

**Comment by jdarcy** [comment]
I don't mind merging the parts that actually might reduce warnings, but I don't see how any of the following changes do so:

(1) Changing functions to "static"

(2) Changing parameters to "const" (actually likely to *increase* warnings)

(3) Casting literal strings to "char *" (under which compiler does this even have any effect?)

**Comment by vtolstov** [comment]
try to compile with:
```
-DNDEBUG -ggdb3 -Wall -Wshadow -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wpointer-arith -Wwrite-strings -Wbad-functio\
n-cast -Wmissing-format-attribute -Wformat=2 -Wformat-security -Wformat-nonliteral -Wno-long-long -Wno-strict-aliasing -Wcast-align -D_GNU_SOURCE -D_LGPL_SOURCE -std=gnu\
99
```

**Comment by vtolstov** [comment]
1) static keywords solves missing-declarations warning
2) const fixes errors like:
```
etcd-api.c:461:34: warning: assignment discards ‘const’ qualifier from pointer target type
                         http_cmd = "DELETE";
```
3) when you try to compile with provided CFLAGS you see.

Also building static library may be very usable.

**Comment by jdarcy** [comment]
1) What version of gcc?  Or is it g++?  If a function is declared non-static, it's still there.  You can see it.  You can link to it.  Clearly it's not missing, and any compiler that says so is mistaken.  It has been a long time since I had trouble with a debugger not seeing "static" functions, but it's not so long since I had to debug problems from that allowing multiple (different) definitions in different files.  I'm not generally a fan of making functions static as a matter of habit, and if non-static functions are showing up undefined in some environment I'd like to understand why.

2) This is specific to -Wwrite-strings, which is a default for g++ but not gcc.

3) I think this is essentially the same as 2.

I'm not strictly opposed to making any of these changes, but if it's to keep a C++ compiler happy then there might be other alternatives (extern "C") or other things that we should do at the same time.

**Comment by vtolstov** [comment]
thanks!

**Pull request merged**
