### PR TITLE
fix locking

### PR DESCRIPTION
**Pull request by vtolstov**
Fix locking issue.

Signed-off-by: Vasiliy Tolstov v.tolstov@selfip.ru

### CODE REVIEW

**Comment by jdarcy** [comment]
Please fix indentation according to the discussion in https://github.com/jdarcy/etcd-api/issues/8.  A little more description of exactly what you're trying to achieve (and how) would be nice too.

**Comment by vtolstov** [comment]
@jdarcy please review it. I'm fix indent and add description.

**Comment by vtolstov** [comment]
ping...

**Comment by jdarcy** [comment]
(1) In etcd_get_one, setting consistent=true should be optional (perhaps
a per-session setting) rather than unconditional.

(2) In etcd_set_one, the actual value of http_cmd will now be the same
whether or not is_lock is true.  The extra checks are fine, but let's
just do all of the assignment in one place.

(3) In etcd_set_one (old line 539, new line 606): why was this condition
changed?  AFAICT the semantics of value and precond have not changed, so
why change the behavior?  Ditto for removing the value check on 636 (old
569).

(4) In etcd_set_one, both halves of the precond conditional at line 637
(old line 570) do the exact same thing.  Might as well not check precond
at all, and if we're doing that then the *is_lock check can be folded
into line 636 (old 569).

**Pull request closed without merging**
